baseURL = "https://stage.solarnetwork.net/"
languageCode = "en-us"
title = "SolarNetwork"
theme = "sn-v1"
description = "SolarNetwork is an open-source platform helping individuals and organisations to track and transform their energy circulation so they can take meaningful action that supports a sustainable future."
Paginate = 4
uglyURLs = true

[params]
  author = "SolarNetwork"
  github = "SolarNetworkFoundation"
  twitter = ""
  email = "info@solarnetwork.net"

[markup.goldmark.parser.attribute]
  block = true
  title = true

[markup.goldmark.renderer]
  unsafe= true

[[menu.main]]
  name = "How it works"
  weight = 100
  identifier = "how-it-works"
  pageRef = "/how-it-works"

[[menu.main]]
  name = "For Developers"
  weight = 200
  identifier = "developers"
  pageRef = "/developers"

[[menu.main]]
  name = "For Homes"
  weight = 300
  identifier = "homes"
  pageRef = "/homes"

[[menu.main]]
  name = "Subscriptions"
  weight = 500
  identifier = "subscriptions"
  pageRef = "/subscriptions"

[[menu.main]]
  name = "Resources"
  weight = 600
  identifier = "resources"
  pageRef = "/resources"

[[menu.main]]
  name = "About"
  weight = 700
  identifier = "about"
  pageRef = "/about"

[[menu.main]]
  name = "Case Studies"
  weight = 900
  identifier = "case-studies"
  pageRef = "/resources/case-studies"
  [menu.main.params]
    hidden = true
